package com.factor.domain.auth;

public enum PermissionCode {
    TENANT_MANAGE,
    ORGANIZATION_MANAGE,
    ACCOUNT_MANAGE,
    ROLE_TEMPLATE_CONFIG,
    PERMISSION_MENU_CONFIG,
    SYSTEM_PARAMETER_CONFIG,
    RISK_THRESHOLD_CONFIG,
    LOG_AUDIT,
    DATA_BACKUP,
    API_KEY_MANAGE,
    FACTOR_READ,
    FACTOR_MANAGE,
    FACTOR_TREE_MANAGE,
    DERIVED_FACTOR_MANAGE,
    STYLE_FACTOR_MANAGE
}
